version: '2'
services:
  db:
    restart: always
    image: postgres:11.6
    expose:
      - "5432"
    volumes:
      - "{{ project_name }}_db_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"

  rabbit:
    restart: always
    image: rabbitmq:3.6.12
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit_user
      - RABBITMQ_DEFAULT_PASS=rabbit_user_default_pass

  {{ project_name }}:
    restart: always
    image: oratio/virgo:latest
    depends_on:
      - redis
      - rabbit
    environment:
      DJANGO_SETTINGS_MODULE: {{ project_name }}.development.settings
      BROKER_URL: amqp://{{ project_name }}:rabbit_line_zap@rabbitmq:5672//
      DJANGOENV: development
      ENVIRONMENT: development
      PYTHON: python
      PROJECT_NAME: {{ project_name }}
      TERM: xterm
      ROLE: development
    links:
      - db:postgres
      - redis:redis
      - rabbit:rabbit
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    expose:
      - "80"
      - "443"
      - "8000"
    volumes:
      - .:/var/www
      - ~/.aws/config:/root/.aws/config
    working_dir: /var/www
    command: bash -lc "pip install invoke jinja2 && invoke -r roles $${ROLE}"

volumes:
  {{ project_name }}_db_data:
    external: true
